# Generated by Django 5.2.6 on 2025-09-24 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News article title', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'championship-2024')", max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt/summary of the article', max_length=500)),
                ('body', models.TextField(help_text='Article content in Markdown format')),
                ('image', models.ImageField(blank=True, help_text='Featured image for the article', null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this article is published')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the article was published', null=True)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Schedule publication for future date/time', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='SEO title (defaults to title if empty)', max_length=60)),
                ('seo_description', models.CharField(blank=True, help_text='SEO description (defaults to body excerpt if empty)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'about', 'faq')", max_length=200, unique=True)),
                ('body', models.TextField(help_text='Page content in Markdown format')),
                ('published', models.BooleanField(default=False, help_text='Whether this page is published')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Schedule publication for future date/time', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='SEO title (defaults to title if empty)', max_length=60)),
                ('seo_description', models.CharField(blank=True, help_text='SEO description (defaults to body excerpt if empty)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title for admin reference', max_length=100)),
                ('image', models.ImageField(help_text='Banner image', upload_to='banners/')),
                ('link_url', models.URLField(blank=True, help_text='Optional link URL when banner is clicked')),
                ('active', models.BooleanField(default=True, help_text='Whether this banner is active')),
                ('starts_at', models.DateTimeField(blank=True, help_text='When to start showing this banner', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='When to stop showing this banner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_published', 'published_at'], name='content_new_is_publ_2f8c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='content_new_slug_8b5b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['published', 'publish_at'], name='content_page_publish_4a8e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='content_page_slug_7b3e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['active', 'starts_at', 'ends_at'], name='content_bann_active_5e8e2a_idx'),
        ),
    ]