# Generated by Django 5.2.6 on 2025-10-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Link display text', max_length=100)),
                ('url', models.URLField(blank=True, help_text='External URL or internal page slug')),
                ('link_type', models.CharField(choices=[('internal', 'Internal Page'), ('external', 'External URL'), ('email', 'Email Address'), ('phone', 'Phone Number')], default='internal', max_length=20)),
                ('section', models.CharField(choices=[('help', 'Help & Support'), ('legal', 'Legal & Policies'), ('company', 'Company'), ('contact', 'Contact'), ('social', 'Social')], default='help', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether link is active')),
                ('opens_in_new_tab', models.BooleanField(default=False, help_text='Open in new tab (external links)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('twitch', 'Twitch')], max_length=20, unique=True)),
                ('url', models.URLField(help_text='Full URL to the social media profile')),
                ('username', models.CharField(blank=True, help_text='Username/handle (without @)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Custom display name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether profile is active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('icon_class', models.CharField(blank=True, help_text="CSS icon class (e.g., 'fab fa-twitter')", max_length=50)),
                ('color', models.CharField(blank=True, help_text="Hex color code (e.g., '#1DA1F2')", max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'platform'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='banner',
            new_name='content_ban_active_3832c1_idx',
            old_name='content_bann_active_5e8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='content_new_is_publ_9c9a8c_idx',
            old_name='content_new_is_publ_2f8c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='content_new_slug_2e5c33_idx',
            old_name='content_new_slug_8b5b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='content_pag_publish_07d50a_idx',
            old_name='content_page_publish_4a8e4c_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='content_pag_slug_23f341_idx',
            old_name='content_page_slug_7b3e4c_idx',
        ),
        migrations.AddIndex(
            model_name='footerlink',
            index=models.Index(fields=['section', 'is_active'], name='content_foo_section_1cb179_idx'),
        ),
        migrations.AddIndex(
            model_name='footerlink',
            index=models.Index(fields=['sort_order'], name='content_foo_sort_or_9eba26_idx'),
        ),
        migrations.AddIndex(
            model_name='socialprofile',
            index=models.Index(fields=['is_active', 'sort_order'], name='content_soc_is_acti_0359c6_idx'),
        ),
    ]
