# Generated by Django 5.2.5 on 2025-09-09 00:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title for admin reference', max_length=100)),
                ('image', models.ImageField(help_text='Banner image', upload_to='banners/')),
                ('link_url', models.URLField(blank=True, help_text='Optional link URL when banner is clicked')),
                ('active', models.BooleanField(default=True, help_text='Whether this banner is active')),
                ('starts_at', models.DateTimeField(blank=True, help_text='When to start showing this banner', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='When to stop showing this banner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News article title', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('body', models.TextField(help_text='Article content in Markdown format')),
                ('published', models.BooleanField(default=False, help_text='Whether this article is published')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Schedule publication for future date/time', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='SEO title (defaults to title if empty)', max_length=60)),
                ('seo_description', models.CharField(blank=True, help_text='SEO description (defaults to body excerpt if empty)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_published',
        ),
        migrations.AddField(
            model_name='page',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Schedule publication for future date/time', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=False, help_text='Whether this page is published'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, help_text='SEO description (defaults to body excerpt if empty)', max_length=160),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title (defaults to title if empty)', max_length=60),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(help_text='Page content in Markdown format'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text="URL-friendly identifier (e.g., 'about', 'faq')", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Page title', max_length=200, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['published', 'publish_at'], name='content_pag_publish_07d50a_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='content_pag_slug_23f341_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['active', 'starts_at', 'ends_at'], name='content_ban_active_3832c1_idx'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published', 'publish_at'], name='content_new_publish_434dd2_idx'),
        ),
    ]
