# Generated by Django 5.2.5 on 2025-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('facilities', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
