# Generated by Django 5.2.6 on 2025-09-16 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique venue name', max_length=200, unique=True)),
                ('address', models.TextField(help_text='Full venue address')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum capacity (0 for unlimited)')),
                ('facilities', models.JSONField(blank=True, help_text='Available facilities (JSON)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this venue', on_delete=django.db.models.deletion.CASCADE, related_name='created_venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VenueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(help_text='Slot start time')),
                ('ends_at', models.DateTimeField(help_text='Slot end time')),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked')], default='available', help_text='Slot availability status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for blocking (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(help_text='Venue this slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='venues.venue')),
            ],
            options={
                'ordering': ['venue', 'starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='venues_venu_name_6dcdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['capacity'], name='venues_venu_capacit_6a742b_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['created_by'], name='venues_venu_created_263d36_idx'),
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['venue', 'starts_at'], name='venues_venu_venue_i_b8408f_idx'),
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['venue', 'status'], name='venues_venu_venue_i_be611f_idx'),
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['starts_at', 'ends_at'], name='venues_venu_starts__39f0e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='venueslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='venue_slot_ends_after_starts'),
        ),
    ]
