# Generated by Django 5.2.6 on 2025-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Venue timezone', max_length=50),
        ),
    ]
