# Generated by Django 5.2.6 on 2025-10-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Maximum capacity (leave blank if unknown; 0 for unlimited)', null=True),
        ),
    ]
