# Generated by Django 5.2.5 on 2025-09-03 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venueavailabilityslot_remove_venue_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(help_text='Slot start time')),
                ('ends_at', models.DateTimeField(help_text='Slot end time')),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked')], default='available', help_text='Slot availability status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for blocking (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['venue', 'starts_at'],
            },
        ),
        migrations.RemoveField(
            model_name='venueavailabilityslot',
            name='venue',
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='venues_venu_city_e9a0b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='venues_venu_is_acti_954204_idx',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='state',
        ),
        migrations.AddField(
            model_name='venue',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this venue', on_delete=django.db.models.deletion.CASCADE, related_name='created_venues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(help_text='Full venue address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum capacity (0 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facilities',
            field=models.JSONField(blank=True, help_text='Available facilities (JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(help_text='Unique venue name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Venue timezone', max_length=50),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['capacity'], name='venues_venu_capacit_6a742b_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['created_by'], name='venues_venu_created_263d36_idx'),
        ),
        migrations.AddField(
            model_name='venueslot',
            name='venue',
            field=models.ForeignKey(help_text='Venue this slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='venues.venue'),
        ),
        migrations.DeleteModel(
            name='VenueAvailabilitySlot',
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['venue', 'starts_at'], name='venues_venu_venue_i_b8408f_idx'),
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['venue', 'status'], name='venues_venu_venue_i_be611f_idx'),
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['starts_at', 'ends_at'], name='venues_venu_starts__39f0e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='venueslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='venue_slot_ends_after_starts'),
        ),
    ]
