# Generated by Django 5.2.5 on 2025-09-03 03:31

from django.db import migrations


def fix_facilities_json(apps, schema_editor):
    """Fix any invalid JSON in the facilities field"""
    Venue = apps.get_model('venues', 'Venue')
    
    for venue in Venue.objects.all():
        if venue.facilities and not isinstance(venue.facilities, dict):
            # If facilities is not a dict, set it to None
            venue.facilities = None
            venue.save()


def reverse_fix_facilities_json(apps, schema_editor):
    """Reverse operation - no need to do anything"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venueavailabilityslot_remove_venue_country_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_facilities_json, reverse_fix_facilities_json),
    ]
