# Generated by Django 5.2.5 on 2025-08-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_add_created_at_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='indoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facilities',
            field=models.TextField(blank=True, help_text="Comma-separated list, e.g. 'parking,locker rooms,first aid'"),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
