# Generated by Django 5.2.5 on 2025-09-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venueslot_remove_venueavailabilityslot_venue_and_more'),
        ('venues', '0004_auto_20250903_1331'),
    ]

    operations = [
    ]
