# Generated by Django 5.2.6 on 2025-09-16 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.event'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['name'], name='api_sport_name_0468a5_idx'),
        ),
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['event'], name='api_announc_event_i_89842a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['sent_at'], name='api_announc_sent_at_5a7446_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['audience'], name='api_announc_audienc_56924c_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['sent_by'], name='api_announc_sent_by_3ea83e_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['event'], name='api_team_event_i_f3be96_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['manager'], name='api_team_manager_9a40d8_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='api_team_name_1be5fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'event')},
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team'], name='api_teammem_team_id_c7093c_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['athlete'], name='api_teammem_athlete_70ffd8_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['jersey_no'], name='api_teammem_jersey__c1aeb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'athlete')},
        ),
    ]
