# Generated by Django 5.2.6 on 2025-09-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='athlete',
        ),
    ]
