# Generated by Django 5.2.6 on 2025-09-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_sport_alter_team_unique_together_and_more'),
        ('fixtures', '0002_alter_fixture_away_alter_fixture_home'),
        ('registrations', '0002_alter_registration_team'),
        ('results', '0002_alter_leaderboardentry_team_alter_result_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
