# Generated by Django 5.2.6 on 2025-09-24 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_team_delete_teammember'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('response_time_ms', models.PositiveIntegerField()),
                ('status_code', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='apimetrics',
            index=models.Index(fields=['endpoint', 'timestamp'], name='api_apimetr_endpoi_8a1b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='apimetrics',
            index=models.Index(fields=['user', 'timestamp'], name='api_apimetr_user_id_9c2b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='apimetrics',
            index=models.Index(fields=['status_code', 'timestamp'], name='api_apimetr_status_8b2b8c_idx'),
        ),
    ]
