# Generated by Django 5.2.6 on 2025-09-24 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250924_1116'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('login', 'Login'), ('logout', 'Logout'), ('role_change', 'Role Change'), ('permission_change', 'Permission Change'), ('data_export', 'Data Export'), ('data_deletion', 'Data Deletion')], help_text='Type of action performed', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='ID of object that was acted upon', null=True)),
                ('target_description', models.CharField(blank=True, help_text='Human-readable description of the target', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        # Skip field removal - table doesn't exist
        migrations.RenameIndex(
            model_name='apimetrics',
            new_name='api_apimetr_endpoin_9725ed_idx',
            old_name='api_apimetr_endpoi_8a1b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='apimetrics',
            new_name='api_apimetr_user_id_2c513e_idx',
            old_name='api_apimetr_user_id_9c2b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='apimetrics',
            new_name='api_apimetr_status__bfaccb_idx',
            old_name='api_apimetr_status_8b2b8c_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='api_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_type',
            field=models.ForeignKey(blank=True, help_text='Type of object that was acted upon', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ratelimit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # Skip model deletion - table doesn't exist
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='api_auditlo_actor_i_57e5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='api_auditlo_action_070bba_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='api_auditlo_target__1f791f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='api_auditlo_timesta_da87a7_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimit',
            index=models.Index(fields=['user', 'endpoint', 'window_start'], name='api_ratelim_user_id_26a3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimit',
            index=models.Index(fields=['ip_address', 'endpoint', 'window_start'], name='api_ratelim_ip_addr_4ef56c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimit',
            unique_together={('ip_address', 'endpoint', 'window_start'), ('user', 'endpoint', 'window_start')},
        ),
    ]
