# Generated by Django 5.2.6 on 2025-10-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auditlog_ratelimit_remove_announcement_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
