# Generated by Django 5.2.6 on 2025-09-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sport name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Sport description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sports_spor_name_4a6fe8_idx'), models.Index(fields=['created_at'], name='sports_spor_created_722083_idx')],
            },
        ),
    ]
