# Generated by Django 5.2.5 on 2025-09-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent of the request'),
        ),
    ]
