# Generated by Django 5.2.5 on 2025-08-21 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('requires_capture', 'Requires Capture'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=255)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('api_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='payments_we_stripe__a54e78_idx'), models.Index(fields=['event_type', 'processed'], name='payments_we_event_t_d02e9d_idx'), models.Index(fields=['created_at'], name='payments_we_created_ef8db8_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__02a25f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_79eeea_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['registration', 'status'], name='payments_pa_registr_63edbb_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['stripe_refund_id'], name='payments_re_stripe__bc040b_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'created_at'], name='payments_re_status_698972_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['registration', 'status'], name='payments_re_registr_dbb6f8_idx'),
        ),
    ]
