# Generated by Django 5.2.6 on 2025-09-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('events', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1, help_text='Round number in tournament')),
                ('phase', models.CharField(choices=[('RR', 'Round Robin'), ('KO', 'Knockout')], default='RR', help_text='Tournament phase', max_length=10)),
                ('start_at', models.DateTimeField(help_text='Fixture start time')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINAL', 'Final')], db_index=True, default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away', models.ForeignKey(blank=True, help_text='Away team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_fixtures', to='api.team')),
                ('event', models.ForeignKey(help_text='Event this fixture belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='events.event')),
                ('home', models.ForeignKey(blank=True, help_text='Home team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_fixtures', to='api.team')),
                ('venue', models.ForeignKey(blank=True, help_text='Fixture venue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='venues.venue')),
            ],
            options={
                'ordering': ['event', 'start_at', 'round'],
                'indexes': [models.Index(fields=['event', 'start_at'], name='fixtures_fi_event_i_d82836_idx'), models.Index(fields=['event', 'round'], name='fixtures_fi_event_i_896bce_idx'), models.Index(fields=['venue', 'start_at'], name='fixtures_fi_venue_i_df8e24_idx'), models.Index(fields=['status'], name='fixtures_fi_status_4477ed_idx'), models.Index(fields=['phase'], name='fixtures_fi_phase_994c6a_idx'), models.Index(fields=['home'], name='fixtures_fi_home_id_b42d01_idx'), models.Index(fields=['away'], name='fixtures_fi_away_id_cab3a3_idx')],
            },
        ),
    ]
