# Generated by Django 5.2.6 on 2025-09-17 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away',
            field=models.ForeignKey(blank=True, help_text='Away team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_fixtures', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home',
            field=models.ForeignKey(blank=True, help_text='Home team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_fixtures', to='teams.team'),
        ),
    ]
