# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fixture_event_start_at ON fixtures_fixture (event_id, start_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_fixture_event_start_at;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fixture_status_start_at ON fixtures_fixture (status, start_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_fixture_status_start_at;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fixture_home_away ON fixtures_fixture (home_id, away_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_fixture_home_away;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fixture_venue_start_at ON fixtures_fixture (venue_id, start_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_fixture_venue_start_at;"
        ),
    ]
