# Generated by Django 5.2.6 on 2025-09-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_add_performance_indexes'),
        ('fixtures', '0002_alter_fixture_away_alter_fixture_home'),
    ]

    operations = [
    ]
