# Generated by Django 5.2.5 on 2025-09-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_venue'),
        ('fixtures', '0002_fixture_matchentry_alter_match_options_and_more'),
        ('teams', '0004_alter_team_created_by'),
        ('venues', '0002_venueavailabilityslot_remove_venue_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='division',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='event',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='venues',
        ),
        migrations.RemoveField(
            model_name='matchentry',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='matchentry',
            name='individual_registration',
        ),
        migrations.RemoveField(
            model_name='matchentry',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchentry',
            name='previous_match',
        ),
        migrations.RemoveField(
            model_name='matchentry',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['event', 'starts_at', 'round_no', 'sequence_no']},
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='fixtures_ma_fixture_2e0ca4_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='fixtures_ma_venue_i_b68589_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='fixtures_ma_status_0bf682_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='fixtures_ma_schedul_cb60a6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division within the event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='events.division'),
        ),
        migrations.AddField(
            model_name='match',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Match duration in minutes'),
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(default=1, help_text='Event this match belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_no',
            field=models.PositiveIntegerField(default=1, help_text='Round number in tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='sequence_no',
            field=models.PositiveIntegerField(default=1, help_text='Order within round'),
        ),
        migrations.AddField(
            model_name='match',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Match start time', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_away_id',
            field=models.ForeignKey(blank=True, help_text='Away team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_home_id',
            field=models.ForeignKey(blank=True, help_text='Home team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_id',
            field=models.ForeignKey(blank=True, help_text='Match venue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='venues.venue'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['event', 'starts_at'], name='fixtures_ma_event_i_3658af_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['venue_id', 'starts_at'], name='fixtures_ma_venue_i_e89f12_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['event', 'division', 'round_no', 'sequence_no'], name='fixtures_ma_event_i_50b4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='fixtures_ma_status_8f0ce0_idx'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='match',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='original_scheduled_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='reschedule_reason',
        ),
        migrations.RemoveField(
            model_name='match',
            name='rescheduled_by',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_number',
        ),
        migrations.RemoveField(
            model_name='match',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Fixture',
        ),
        migrations.DeleteModel(
            name='MatchEntry',
        ),
    ]
