# Generated by Django 5.2.5 on 2025-08-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_eligibility_criteria_event_eligibility_notes_and_more'),
        ('fixtures', '0003_add_created_at_field'),
        ('teams', '0002_remove_athleteprofile_stats_remove_team_event_and_more'),
        ('venues', '0002_alter_venue_address_alter_venue_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='venues.venue'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['venue', 'start_time'], name='fixtures_ma_venue_i_05a4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['venue', 'start_time', 'end_time'], name='fixtures_ma_venue_i_75251e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['event', 'start_time'], name='fixtures_ma_event_i_797a4b_idx'),
        ),
    ]
