# Generated by Django 5.2.5 on 2025-09-03 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_venue'),
        ('fixtures', '0003_remove_fixture_division_remove_fixture_event_and_more'),
        ('teams', '0005_auto_20250903_1143'),
        ('venues', '0003_venueslot_remove_venueavailabilityslot_venue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='division',
        ),
        migrations.RemoveField(
            model_name='match',
            name='event',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_away_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_home_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue_id',
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(default=1, help_text='Round number in tournament')),
                ('starts_at', models.DateTimeField(help_text='Fixture start time')),
                ('ends_at', models.DateTimeField(help_text='Fixture end time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event this fixture belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='events.event')),
                ('venue', models.ForeignKey(blank=True, help_text='Fixture venue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='venues.venue')),
            ],
            options={
                'ordering': ['event', 'starts_at', 'round_no'],
            },
        ),
        migrations.CreateModel(
            name='FixtureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], help_text='Home or away side', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(help_text='Fixture this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fixtures.fixture')),
                ('participant', models.ForeignKey(blank=True, help_text='Individual participant (if individual-based)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_entries', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team (if team-based)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_entries', to='teams.team')),
            ],
            options={
                'ordering': ['fixture', 'side'],
            },
        ),
    ]
