# Generated by Django 5.2.6 on 2025-09-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_merge_20250917_1625'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE fixtures_fixture RENAME COLUMN starts_at TO start_at;",
            reverse_sql="ALTER TABLE fixtures_fixture RENAME COLUMN start_at TO starts_at;"
        ),
        migrations.RunSQL(
            "ALTER TABLE fixtures_fixture RENAME COLUMN round_no TO round;",
            reverse_sql="ALTER TABLE fixtures_fixture RENAME COLUMN round TO round_no;"
        ),
    ]
