# Generated by Django 5.2.5 on 2025-08-14 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_make_teams_nullable_and_add_end_time'),
        ('teams', '0002_remove_athleteprofile_stats_remove_team_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='teams.team'),
        ),
    ]
