# Generated by Django 5.2.6 on 2025-09-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_auto_20250923_1305'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE fixtures_fixture ADD COLUMN phase VARCHAR(10) DEFAULT 'RR';",
            reverse_sql="ALTER TABLE fixtures_fixture DROP COLUMN phase;"
        ),
        migrations.RunSQL(
            "ALTER TABLE fixtures_fixture ADD COLUMN home_id INTEGER REFERENCES teams_team(id) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE fixtures_fixture DROP COLUMN home_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE fixtures_fixture ADD COLUMN away_id INTEGER REFERENCES teams_team(id) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE fixtures_fixture DROP COLUMN away_id;"
        ),
    ]
