# Generated by Django 5.2.5 on 2025-09-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_remove_match_division_remove_match_event_and_more'),
        ('gallery', '0002_remove_album_match_album_fixture'),
        ('results', '0002_rename_score_a_result_score_away_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['event', 'starts_at'], name='fixtures_fi_event_i_827807_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['event', 'round_no'], name='fixtures_fi_event_i_d66054_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['venue', 'starts_at'], name='fixtures_fi_venue_i_f7bc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['status'], name='fixtures_fi_status_4477ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='fixture',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='fixture_ends_after_starts'),
        ),
        migrations.AddIndex(
            model_name='fixtureentry',
            index=models.Index(fields=['fixture', 'side'], name='fixtures_fi_fixture_813b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='fixtureentry',
            index=models.Index(fields=['team'], name='fixtures_fi_team_id_3e46ea_idx'),
        ),
        migrations.AddIndex(
            model_name='fixtureentry',
            index=models.Index(fields=['participant'], name='fixtures_fi_partici_3630b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='fixtureentry',
            constraint=models.UniqueConstraint(fields=('fixture', 'side'), name='unique_fixture_side'),
        ),
        migrations.AddConstraint(
            model_name='fixtureentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participant__isnull', True), ('team__isnull', False)), models.Q(('participant__isnull', False), ('team__isnull', True)), _connector='OR'), name='fixture_entry_team_or_participant'),
        ),
    ]
