# Generated by Django 5.2.5 on 2025-08-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_eligibility_criteria_event_eligibility_notes_and_more'),
        ('fixtures', '0005_alter_match_end_time_alter_match_status_and_more'),
        ('teams', '0002_remove_athleteprofile_stats_remove_team_event_and_more'),
        ('venues', '0004_alter_venue_options_venue_city_venue_country_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='fixtures_ma_venue_i_05a4a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='fixtures_ma_venue_i_75251e_idx',
        ),
        migrations.AddField(
            model_name='match',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=12),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='venues.venue'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='fixtures_ma_status_8f0ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['is_published'], name='fixtures_ma_is_publ_cfaac1_idx'),
        ),
    ]
