# Generated by Django 5.2.6 on 2025-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_announcement_options_alter_event_options_and_more'),
        ('fixtures', '0005_auto_20250923_1307'),
        ('teams', '0003_team_is_active_team_is_public_team_sport'),
        ('venues', '0002_venue_timezone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['status', 'start_at'], name='fixtures_fi_status_46ff81_idx'),
        ),
    ]
