# Generated by Django 5.2.5 on 2025-08-19 04:48

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixtures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Total price in cents.')),
                ('qr_code', models.CharField(db_index=True, default=tickets.models.generate_qr_code, help_text='Unique QR token for validation.', max_length=64, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REFUNDED', 'Refunded'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=10)),
                ('match', models.ForeignKey(blank=True, help_text='Match this ticket grants entry to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='fixtures.match')),
                ('purchaser', models.ForeignKey(help_text='User who purchased the ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['purchaser', 'purchased_at'], name='tickets_tic_purchas_9a31b5_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'), models.Index(fields=['match'], name='tickets_tic_match_i_3dc61d_idx')],
            },
        ),
    ]
