# Generated by Django 5.2.5 on 2025-08-14 00:22

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_remove_match_round_name_remove_match_status_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='purchaser',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='fixtures.match'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.CharField(db_index=True, default=tickets.models.generate_qr_code, max_length=64, unique=True),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price_paid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
    ]
