# Generated by Django 5.2.5 on 2025-09-03 03:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_venue'),
        ('fixtures', '0005_delete_match_fixture_fixtures_fi_event_i_827807_idx_and_more'),
        ('tickets', '0002_create_missing_tables_sql'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['event', 'fixture', 'price_cents']},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_ticket__5a4a00_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_order_i_ccd08a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_ticket__0ca21b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_validat_619851_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketorder',
            name='tickets_tic_custome_013831_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketorder',
            name='tickets_tic_order_n_d35cbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketorder',
            name='tickets_tic_payment_fb8b80_idx',
        ),
        migrations.RemoveIndex(
            model_name='tickettype',
            name='tickets_tic_event_i_4b23ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='tickettype',
            name='tickets_tic_sale_st_ed6bfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='tickettype',
            name='tickets_tic_categor_24be36_idx',
        ),
        migrations.RenameField(
            model_name='ticketorder',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='holder_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='holder_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='section',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='validation_hash',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='payment_amount_cents',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='payment_currency',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='provider_reference',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='includes_amenities',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='includes_seating',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_transferable',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='max_per_order',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='sale_end',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='sale_start',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='sold_quantity',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_payload',
            field=models.TextField(default=1, help_text='QR code payload string'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='serial',
            field=models.CharField(default=1111, help_text='Human-readable ticket serial', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_orders', to='fixtures.fixture'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='provider_payment_intent',
            field=models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='provider_session_id',
            field=models.CharField(blank=True, help_text='Stripe session ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='total_cents',
            field=models.PositiveIntegerField(default=1, help_text='Total amount in cents', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='fixtures.fixture'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='on_sale',
            field=models.BooleanField(default=True, help_text='Whether tickets are on sale'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0, help_text='Quantity sold', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='quantity_total',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity available', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('used', 'Used'), ('void', 'Void')], db_index=True, default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When ticket was used', null=True),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True, help_text='Ticket description'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(help_text='Ticket type name', max_length=200),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price_cents',
            field=models.PositiveIntegerField(help_text='Price in cents', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order'], name='tickets_tic_order_i_6d066f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type'], name='tickets_tic_ticket__612fec_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['serial'], name='tickets_tic_serial_04c73c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['user', 'status'], name='tickets_tic_user_id_4b5d07_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['fixture', 'status'], name='tickets_tic_fixture_4fd8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['provider_session_id'], name='tickets_tic_provide_e57396_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'fixture', 'on_sale'], name='tickets_tic_event_i_fe8b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'on_sale'], name='tickets_tic_event_i_3fdac7_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['fixture', 'on_sale'], name='tickets_tic_fixture_20c9be_idx'),
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
