# Generated by Django 5.2.5 on 2025-08-14 01:41

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_remove_match_round_name_remove_match_status_and_more'),
        ('tickets', '0002_rename_user_ticket_purchaser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-purchased_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REFUNDED', 'Refunded'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Match this ticket grants entry to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='fixtures.match'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Total price in cents.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchaser',
            field=models.ForeignKey(help_text='User who purchased the ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.CharField(db_index=True, default=tickets.models.generate_qr_code, help_text='Unique QR token for validation.', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['purchaser', 'purchased_at'], name='tickets_tic_purchas_9a31b5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['match'], name='tickets_tic_match_i_3dc61d_idx'),
        ),
    ]
