# Generated by Django 5.2.6 on 2025-10-01 02:03

from django.db import migrations, models
from django.db.models import deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=deletion.CASCADE, related_name='tickets', to='tickets.ticketorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=deletion.CASCADE, related_name='tickets', to='tickets.tickettype'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='code',
            new_name='serial',
        ),
    ]
