# Generated by Django 5.2.5 on 2025-09-09 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_paymentrecord_order_alter_tickettype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='provider_payment_intent',
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('offline', 'Offline Bank Transfer')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='provider_payment_intent_id',
            field=models.CharField(blank=True, help_text='Payment provider payment intent ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='provider_session_id',
            field=models.CharField(blank=True, help_text='Payment provider session ID', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(help_text='Refund amount in cents')),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('provider_refund_id', models.CharField(blank=True, help_text='Provider refund ID', max_length=255, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Provider response data')),
                ('reason', models.TextField(blank=True, help_text='Refund reason')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='tickets.ticketorder')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='tickets_ref_order_i_b319e2_idx'), models.Index(fields=['processed_by', 'status'], name='tickets_ref_process_1862c4_idx'), models.Index(fields=['status', 'created_at'], name='tickets_ref_status_29a886_idx')],
            },
        ),
    ]
