# Generated by Django 5.2.6 on 2025-10-01 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20251001_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='purchase',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket Order', 'verbose_name_plural': 'Ticket Orders'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket Type', 'verbose_name_plural': 'Ticket Types'},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_purchas_1d7a2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_code_2520cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketorder',
            name='tickets_tic_fixture_4fd8b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketorder',
            name='tickets_tic_provide_e57396_idx',
        ),
        migrations.RemoveIndex(
            model_name='tickettype',
            name='tickets_tic_event_i_fe8b2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='tickettype',
            name='tickets_tic_event_i_3fdac7_idx',
        ),
        migrations.RemoveIndex(
            model_name='tickettype',
            name='tickets_tic_fixture_20c9be_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='serial',
            field=models.CharField(help_text='Unique ticket serial number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('offline', 'Offline')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='provider_payment_intent_id',
            field=models.CharField(blank=True, help_text='Payment provider intent ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='provider_session_id',
            field=models.CharField(blank=True, help_text='Payment provider session ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='total_cents',
            field=models.PositiveIntegerField(help_text='Total amount in cents'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True, help_text='Ticket type description'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(help_text='Ticket type name', max_length=100),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price_cents',
            field=models.PositiveIntegerField(help_text='Price in cents'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0, help_text='Quantity sold'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity_total',
            field=models.PositiveIntegerField(help_text='Total quantity available'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['serial'], name='tickets_tic_serial_04c73c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['provider_payment_intent_id'], name='tickets_tic_provide_e0464d_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event_id'], name='tickets_tic_event_i_83b341_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['fixture_id'], name='tickets_tic_fixture_07894b_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['on_sale'], name='tickets_tic_on_sale_455f49_idx'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
