# Generated by Django 5.2.6 on 2025-10-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_purchase_user_remove_ticket_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, help_text='Ticket code for display', max_length=50),
        ),
    ]
