# Generated by Django 5.2.6 on 2025-10-01 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_order_ticket_ticket_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticketorder',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_intent_id__gt', '')), fields=('provider_payment_intent_id',), name='unique_payment_intent'),
        ),
    ]
