# Generated by Django 5.2.6 on 2025-10-01 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketorder_unique_payment_intent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When ticket was approved', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Organizer who approved this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='client_reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique reference for this order', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('valid', 'Valid'), ('used', 'Used'), ('void', 'Void')], db_index=True, default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='provider_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment provider session ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('pending', 'Pending'), ('paid', 'Paid'), ('free', 'Free'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='payment_pending', max_length=20),
        ),
    ]
