# Generated by Django 5.2.6 on 2025-09-17 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_alter_event_sport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Team description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, help_text='Team coach', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='Event this team participates in', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
                ('manager', models.ForeignKey(help_text='Team manager', on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_no', models.PositiveIntegerField(help_text='Jersey number')),
                ('position', models.CharField(blank=True, help_text='Player position', max_length=50)),
                ('is_captain', models.BooleanField(default=False, help_text='Whether this member is the team captain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(help_text='Athlete user', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['jersey_no'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['event'], name='teams_team_event_i_64c3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['manager'], name='teams_team_manager_77d289_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['coach'], name='teams_team_coach_i_a1be68_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='teams_team_name_43e047_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_at'], name='teams_team_created_d2426c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'event')},
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team'], name='teams_teamm_team_id_015042_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['athlete'], name='teams_teamm_athlete_df503b_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['jersey_no'], name='teams_teamm_jersey__145b56_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_captain'], name='teams_teamm_is_capt_a12c03_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['created_at'], name='teams_teamm_created_0e1ac0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'athlete'), ('team', 'jersey_no')},
        ),
    ]
