# Generated by Django 5.2.5 on 2025-08-14 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='sport',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='teams.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
