# Generated by Django 5.2.6 on 2025-09-23 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='teams',
                to='events.event',
                help_text='Event this team participates in',
                null=True,  # Allow null temporarily
                blank=True
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='teams',
                to='events.event',
                help_text='Event this team participates in',
                null=False,  # Make it required after data migration
                blank=False
            ),
        ),
    ]
