# Generated by Django 5.2.5 on 2025-08-21 18:22

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def set_default_values(apps, schema_editor):
    """Set default values for existing teams"""
    Team = apps.get_model('teams', 'Team')
    for team in Team.objects.all():
        if not hasattr(team, 'sport'):
            team.sport = 'General'
        team.save()


def reverse_default_values(apps, schema_editor):
    """Reverse the default value setting"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        # Add new fields with defaults
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(max_length=100, default='General', help_text='Sport this team plays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founded_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='home_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_teams', to='venues.venue'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='total_matches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to='accounts.user'),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['sport', 'is_active'], name='teams_team_sport_i_123456_idx'),
        ),
        
        # Run data migration
        migrations.RunPython(set_default_values, reverse_default_values),
    ]
