# Generated by Django 5.2.6 on 2025-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20250923_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether team is active'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether team is public'),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(default='General', help_text='Sport type', max_length=100),
        ),
    ]
