# Generated by hand to fix missing athlete_id column in teams_teammember
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_is_active_team_is_public_team_sport'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            -- Add column if missing
            ALTER TABLE teams_teammember
            ADD COLUMN IF NOT EXISTS athlete_id bigint;

            -- Create index if missing
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relkind = 'i'
                      AND c.relname = 'teams_teamm_athlete_df503b_idx'
                ) THEN
                    CREATE INDEX teams_teamm_athlete_df503b_idx ON teams_teammember(athlete_id);
                END IF;
            END$$;

            -- Add FK constraint if missing
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'teams_teammember_athlete_id_fk'
                ) THEN
                    ALTER TABLE teams_teammember
                    ADD CONSTRAINT teams_teammember_athlete_id_fk
                    FOREIGN KEY (athlete_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END$$;
            ''',
            reverse_sql='''
            -- Safe reverse: drop FK if exists (do not drop column automatically)
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'teams_teammember_athlete_id_fk'
                ) THEN
                    ALTER TABLE teams_teammember DROP CONSTRAINT teams_teammember_athlete_id_fk;
                END IF;
            END$$;
            ''',
        ),
    ]


