# Generated by Django 5.2.5 on 2025-09-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_created_by'),
    ]

    operations = [
    ]
