# Generated by Django 5.2.5 on 2025-09-03 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_venue'),
        ('teams', '0005_auto_20250903_1143'),
        ('venues', '0003_venueslot_remove_venueavailabilityslot_venue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('decided_at', models.DateTimeField(blank=True, help_text='When the entry was decided', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_team_sport_12bd8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_team_created_9adf4c_idx',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, help_text='Team coach (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_email',
            field=models.EmailField(default=1, help_text='Team contact email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Team contact phone', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(default=1, help_text='Team manager', on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age verification', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(default=1, help_text='Full name of the team member', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('SUSPENDED', 'Suspended'), ('INJURED', 'Injured')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user account (optional for standalone profiles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='teams_team_name_43e047_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['sport', 'name'], name='teams_team_sport_3b514f_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['manager'], name='teams_team_manager_77d289_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['coach'], name='teams_team_coach_i_a1be68_idx'),
        ),
        migrations.AddField(
            model_name='teamevententry',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='User who made the decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_team_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamevententry',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Specific division (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_entries', to='events.division'),
        ),
        migrations.AddField(
            model_name='teamevententry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_entries', to='events.event'),
        ),
        migrations.AddField(
            model_name='teamevententry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_entries', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='teamevententry',
            index=models.Index(fields=['team', 'event', 'status'], name='teams_teame_team_id_c3c506_idx'),
        ),
        migrations.AddIndex(
            model_name='teamevententry',
            index=models.Index(fields=['event', 'status'], name='teams_teame_event_i_2c9c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='teamevententry',
            index=models.Index(fields=['status'], name='teams_teame_status_731465_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamevententry',
            unique_together={('team', 'event', 'division')},
        ),
    ]
