# Generated by Django 5.2.6 on 2025-10-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_add_is_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('captain', 'Captain'), ('coach', 'Coach'), ('manager', 'Manager')], default='player', help_text='Role of the team member', max_length=20),
        ),
    ]
