# Generated by Django 5.2.6 on 2025-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Member status', max_length=20),
        ),
    ]
