# Generated by Django 5.2.6 on 2025-10-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_teammember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='joined_date',
            field=models.DateField(auto_now_add=True, help_text='Date when member joined the team', null=True),
        ),
    ]
