# Generated by Django 5.2.6 on 2025-09-17 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key', max_length=100, unique=True)),
                ('value', models.JSONField(help_text='Setting value (can be any JSON-serializable type)')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting does')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this setting can be accessed by non-admin users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CANCEL', 'Cancel'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('BULK_ACTION', 'Bulk Action')], help_text='Type of action performed', max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='ID of the object that was acted upon', null=True)),
                ('target_description', models.CharField(blank=True, help_text='Human-readable description of the target object', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action (changes, metadata, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('actor', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(blank=True, help_text='Type of object that was acted upon', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='common_audi_actor_i_268ebf_idx'), models.Index(fields=['action', 'timestamp'], name='common_audi_action_6014bc_idx'), models.Index(fields=['target_type', 'target_id'], name='common_audi_target__79ac9b_idx'), models.Index(fields=['timestamp'], name='common_audi_timesta_4ebe40_idx')],
            },
        ),
    ]
