# Generated by Django 5.2.6 on 2025-09-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.ForeignKey(blank=True, help_text='Type of object that was acted upon', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_audit_logs', to='contenttypes.contenttype'),
        ),
    ]
