# Generated by Django 5.2.6 on 2025-09-16 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                ('eligibility', models.JSONField(blank=True, default=dict, help_text='Eligibility criteria (JSON)')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], db_index=True, default='UPCOMING', help_text='Event status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(help_text='Sport type', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.sport')),
                ('venue', models.ForeignKey(blank=True, help_text='Associated venue (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.venue')),
            ],
            options={
                'ordering': ['start_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Division name', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order for display')),
                ('event', models.ForeignKey(help_text='Parent event', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_date'], name='events_even_status_dfba18_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['sport'], name='events_even_sport_i_8f45b5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue'], name='events_even_venue_i_f3b114_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='events_even_created_95418c_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['event', 'sort_order'], name='events_divi_event_i_c9a385_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('event', 'name')},
        ),
    ]
