# Generated by Django 5.2.5 on 2025-08-13 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport_type', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('ZONAL', 'Zonal'), ('DISTRICT', 'District'), ('NATIONAL', 'National')], default='DISTRICT', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=12)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('is_ticketed', models.BooleanField(default=False)),
                ('base_ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='venues.venue')),
            ],
        ),
    ]
