# Generated by Django 5.2.5 on 2025-08-14 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eligibility_criteria',
            new_name='eligibility_notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='base_ticket_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_ticketed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='level',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=10),
        ),
    ]
