# Generated by Django 5.2.6 on 2025-09-17 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_status'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(help_text='Sport type', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sports.sport'),
        ),
    ]
