# Generated by Django 5.2.5 on 2025-09-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_division_alter_event_options_event_capacity_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='division',
            new_name='events_divi_event_i_c9a385_idx',
            old_name='events_divis_event__sort_o_8b4b8b_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_start_d_b72861_idx',
            old_name='events_even_start_d_8b4b8b_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_lifecyc_0f97b3_idx',
            old_name='events_even_lifecyc_8b4b8b_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_lifecyc_f42fd7_idx',
            old_name='events_even_lifecyc_start_d_8b4b8b_idx',
        ),
    ]
