# Generated by Django 5.2.5 on 2025-09-02 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_events_divis_event__sort_o_8b4b8b_idx_events_divi_event_i_c9a385_idx_and_more'),
        ('venues', '0002_venueavailabilityslot_remove_venue_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Associated venue (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.venue'),
        ),
    ]
