# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_visibility'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_event_status_start_date ON events_event (status, start_datetime);",
            reverse_sql="DROP INDEX IF EXISTS idx_event_status_start_date;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_event_visibility_status ON events_event (visibility, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_event_visibility_status;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_event_created_by_status ON events_event (created_by_id, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_event_created_by_status;"
        ),
    ]
