# Generated by Django 5.2.6 on 2025-09-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_announcement_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether ticket purchases require approval'),
        ),
    ]
