# Generated by Django 5.2.6 on 2025-09-24 05:40

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_requires_approval_field'),
    ]

    operations = [
        # Add new datetime fields with default values
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(help_text='Event start date and time', default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(help_text='Event end date and time', default=timezone.now),
            preserve_default=False,
        ),
        # Copy data from old fields to new fields
        migrations.RunSQL(
            "UPDATE events_event SET start_datetime = start_date, end_datetime = end_date;",
            reverse_sql="UPDATE events_event SET start_date = start_datetime, end_date = end_datetime;"
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
