# Generated by Django 5.2.6 on 2025-09-24 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20250924_1540'),
        ('teams', '0003_team_is_active_team_is_public_team_sport'),
        ('venues', '0002_venue_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_start_d_d4b514_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_status_dfba18_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_sport_c790f5_idx',
            old_name='events_even_sport_i_8f45b5_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eligibility',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum capacity', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='Registration fee in cents'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Event location', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_close_at',
            field=models.DateTimeField(blank=True, help_text='Registration close date', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open_at',
            field=models.DateTimeField(blank=True, help_text='Registration open date', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this announcement', on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(help_text='Event this announcement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.event'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When announcement expires (null = never)', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether announcement is currently active'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether announcement is visible to all event participants'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(help_text='Announcement message'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Announcement priority', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_teams',
            field=models.ManyToManyField(blank=True, help_text='Specific teams to target (empty = all teams)', related_name='announcements', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Announcement title', max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SCHEDULE', 'Schedule Change'), ('RESULT', 'Result Update'), ('WEATHER', 'Weather Alert'), ('EMERGENCY', 'Emergency')], default='GENERAL', help_text='Type of announcement', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Event end date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(help_text='Sport type', max_length=100),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['event', 'is_active'], name='events_anno_event_i_a1a147_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['event', 'priority'], name='events_anno_event_i_5e1a38_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='events_anno_created_c782d4_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['expires_at'], name='events_anno_expires_7fe2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='events_even_start_d_b72861_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_datetime'], name='events_even_status_02a0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility', 'status'], name='events_even_visibil_349c85_idx'),
        ),
    ]
