# Generated by Django 5.2.5 on 2025-08-20 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_division_alter_event_options_event_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team')], default='INDIVIDUAL', max_length=12)),
                ('team_name', models.CharField(blank=True, help_text='Required for team registrations', max_length=100)),
                ('team_members', models.JSONField(blank=True, default=list, help_text='List of team member details')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('WAITLISTED', 'Waitlisted'), ('PAYMENT_PENDING', 'Payment Pending'), ('KYC_PENDING', 'KYC Verification Pending')], db_index=True, default='PAYMENT_PENDING', max_length=20)),
                ('kyc_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='NOT_STARTED', max_length=20)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or allergies')),
                ('dietary_requirements', models.TextField(blank=True, help_text='Special dietary needs')),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255)),
                ('payment_amount_cents', models.PositiveIntegerField(default=0, help_text='Amount paid in cents')),
                ('payment_currency', models.CharField(default='AUD', help_text='Payment currency code', max_length=3)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('organizer_notes', models.TextField(blank=True, help_text='Internal notes for organizers')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.division')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('kyc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verified_registrations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='registratio_status_d5c3be_idx'), models.Index(fields=['event', 'status'], name='registratio_event_i_246b4a_idx'), models.Index(fields=['user', 'status'], name='registratio_user_id_e3aac6_idx'), models.Index(fields=['kyc_status', 'status'], name='registratio_kyc_sta_13b214_idx'), models.Index(fields=['stripe_payment_intent_id'], name='registratio_stripe__9c449d_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
