# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_registration_event_status ON registrations_registration (event_id, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_registration_event_status;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_registration_applicant_status ON registrations_registration (applicant_id, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_registration_applicant_status;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_registration_team_status ON registrations_registration (team_id, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_registration_team_status;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_registration_created_at ON registrations_registration (created_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_registration_created_at;"
        ),
    ]
