
# Generated by Django 5.2.5 on 2025-08-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_eligibility_criteria_event_eligibility_notes_and_more'),
        ('registrations', '0001_initial'),
        ('teams', '0002_remove_athleteprofile_stats_remove_team_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='paid',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_ref',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='registration',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('event', 'team'), name='uniq_event_team'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('athlete__isnull', False)), fields=('event', 'athlete'), name='uniq_event_athlete'),
        ),
    ]
