# Generated by Django 5.2.5 on 2025-09-02 06:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import registrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_events_divis_event__sort_o_8b4b8b_idx_events_divi_event_i_c9a385_idx_and_more'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_card', 'ID Card'), ('medical_clearance', 'Medical Clearance'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=registrations.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Notes about the document')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], max_length=10)),
                ('provider_ref', models.CharField(help_text='Provider reference (e.g., Stripe payment intent ID)', max_length=255)),
                ('kind', models.CharField(choices=[('intent', 'Payment Intent'), ('confirm', 'Payment Confirmation'), ('refund', 'Refund')], max_length=10)),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(help_text='Payment status from provider', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='registratio_status_d5c3be_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='registratio_event_i_246b4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='registratio_user_id_e3aac6_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='registratio_kyc_sta_13b214_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='registratio_stripe__9c449d_idx',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='kyc_verified_at',
            new_name='decided_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='dietary_requirements',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='kyc_verified_by',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='organizer_notes',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_amount_cents',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_currency',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_type',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='Registration fee in cents'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for rejection or other notes'),
        ),
        migrations.AddField(
            model_name='registration',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='team_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=12),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waitlisted', 'Waitlisted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event'], name='registratio_event_i_c30af8_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', 'event'], name='registratio_user_id_afd0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='registratio_status_42419d_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['payment_status'], name='registratio_payment_d80905_idx'),
        ),
        migrations.AddField(
            model_name='registrationdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationdocument',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registrations.registration'),
        ),
        migrations.AddField(
            model_name='registrationpaymentlog',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='registrations.registration'),
        ),
        migrations.AddIndex(
            model_name='registrationdocument',
            index=models.Index(fields=['registration'], name='registratio_registr_790767_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationdocument',
            index=models.Index(fields=['doc_type'], name='registratio_doc_typ_fc9cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationpaymentlog',
            index=models.Index(fields=['registration'], name='registratio_registr_d87440_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationpaymentlog',
            index=models.Index(fields=['provider_ref'], name='registratio_provide_b8e29d_idx'),
        ),
    ]
