# Generated by Django 5.2.6 on 2025-09-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_add_performance_indexes'),
        ('registrations', '0002_alter_registration_team'),
    ]

    operations = [
    ]
