# Generated by Django 5.2.6 on 2025-09-23 03:10

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def migrate_applicant_data(apps, schema_editor):
    """Migrate data from applicant to applicant_user"""
    Registration = apps.get_model('registrations', 'Registration')
    
    # Migrate athlete registrations
    for registration in Registration.objects.filter(type='ATHLETE', applicant__isnull=False):
        registration.applicant_user = registration.applicant
        registration.save(update_fields=['applicant_user'])
    
    # Migrate team registrations
    for registration in Registration.objects.filter(type='TEAM', team__isnull=False):
        registration.applicant_team = registration.team
        registration.save(update_fields=['applicant_team'])


def reverse_migrate_applicant_data(apps, schema_editor):
    """Reverse migration - move data back to legacy fields"""
    Registration = apps.get_model('registrations', 'Registration')
    
    # Move applicant_user back to applicant
    for registration in Registration.objects.filter(applicant_user__isnull=False):
        registration.applicant = registration.applicant_user
        registration.save(update_fields=['applicant'])
    
    # Move applicant_team back to team
    for registration in Registration.objects.filter(applicant_team__isnull=False):
        registration.team = registration.applicant_team
        registration.save(update_fields=['team'])


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_merge_20250917_1625'),
        ('teams', '0002_auto_20250923_1303'),  # Ensure teams app is migrated
    ]

    operations = [
        # Step 1: Add new fields (nullable initially)
        migrations.AddField(
            model_name='registration',
            name='applicant_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_registrations',
                to=settings.AUTH_USER_MODEL,
                help_text='User applicant for athlete registrations'
            ),
        ),
        migrations.AddField(
            model_name='registration',
            name='applicant_team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='team_registrations',
                to='teams.team',
                help_text='Team applicant for team registrations'
            ),
        ),
        
        # Step 2: Add indexes for new fields
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['applicant_user'], name='registratio_applica_2a1b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['applicant_team'], name='registratio_applica_3c2d4e_idx'),
        ),
        
        # Step 3: Migrate data from legacy fields to new fields
        migrations.RunPython(
            migrate_applicant_data,
            reverse_migrate_applicant_data,
        ),
        
        # Step 4: Add constraint (but don't enforce yet to allow legacy data)
        # We'll add the constraint in a separate migration after we're sure everything works
    ]
