# Generated by Django 5.2.5 on 2025-08-14 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_eligibility_criteria_event_eligibility_notes_and_more'),
        ('registrations', '0004_add_user_field_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='uniq_event_team',
        ),
        migrations.RemoveConstraint(
            model_name='registration',
            name='uniq_event_athlete',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'event')},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team',
        ),
    ]
