# Generated by Django 5.2.6 on 2025-09-23 03:44

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_add_applicant_fields'),
    ]

    operations = [
        # Make the legacy applicant field nullable to allow new fields to work
        migrations.AlterField(
            model_name='registration',
            name='applicant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='registrations',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
