# Generated by Django 5.2.6 on 2025-09-24 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_announcement_options_alter_event_options_and_more'),
        ('registrations', '0005_fix_applicant_nullable'),
        ('teams', '0003_team_is_active_team_is_public_team_sport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registration',
            new_name='registratio_applica_cc66c0_idx',
            old_name='registratio_applica_2a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='registration',
            new_name='registratio_applica_7319c3_idx',
            old_name='registratio_applica_3c2d4e_idx',
        ),
        migrations.AddField(
            model_name='registration',
            name='fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='Registration fee in cents'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status', 'submitted_at'], name='registratio_status_7b9521_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applicant_user__isnull', False), ('applicant_team__isnull', True)), models.Q(('applicant_user__isnull', True), ('applicant_team__isnull', False)), _connector='OR'), name='exactly_one_applicant'),
        ),
    ]
