# Generated by Django 5.2.6 on 2025-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_update_exactly_one_applicant_for_spectator'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='exactly_one_applicant',
        ),
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('TEAM', 'Team'), ('ATHLETE', 'Athlete'), ('SPECTATOR', 'Spectator')], default='ATHLETE', max_length=10),
        ),
    ]
