# Generated by Django 5.2.6 on 2025-10-01 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_announcement_options_alter_event_options_and_more'),
        ('registrations', '0008_remove_registration_exactly_one_applicant_and_more'),
        ('teams', '0007_teammember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'ATHLETE'), ('applicant_user__isnull', False), ('applicant_team__isnull', True)), models.Q(('type', 'TEAM'), ('applicant_user__isnull', True), ('applicant_team__isnull', False)), models.Q(('type', 'SPECTATOR'), ('applicant_user__isnull', True), ('applicant_team__isnull', True)), _connector='OR'), name='exactly_one_applicant'),
        ),
    ]
