# Generated by Django 5.2.6 on 2025-09-24 05:41

import gallery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_announcement_options_alter_event_options_and_more'),
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Item', 'verbose_name_plural': 'Media Items'},
        ),
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Legacy Media Asset', 'verbose_name_plural': 'Legacy Media Assets'},
        ),
        migrations.RemoveIndex(
            model_name='media',
            name='gallery_media_event_id_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='media',
            name='gallery_media_fixture_id_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='media',
            name='gallery_media_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='media',
            new_name='gallery_med_uploade_6d3e8d_idx',
            old_name='gallery_media_uploaded_by_created_at_idx',
        ),
        migrations.RemoveField(
            model_name='media',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='media',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='media',
            name='status',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title',
        ),
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, help_text='Media caption', max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether media is approved'),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], default='image', help_text='Type of media', max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(help_text='Media file', upload_to=gallery.models.Media.media_upload_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=gallery.models.media_upload_path),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['event', 'is_approved'], name='gallery_med_event_i_9b87be_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['is_approved', 'created_at'], name='gallery_med_is_appr_3d540c_idx'),
        ),
    ]
