# Generated by Django 5.2.5 on 2025-09-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_remove_match_division_remove_match_event_and_more'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='match',
        ),
        migrations.AddField(
            model_name='album',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='fixtures.fixture'),
        ),
    ]
