# Generated by Django 5.2.6 on 2025-10-01 03:06

import django.db.models.deletion
import gallery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_media_options_alter_mediaasset_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Album title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Album description')),
                ('cover', models.ImageField(blank=True, help_text='Album cover image', null=True, upload_to='gallery/albums/covers/')),
                ('is_public', models.BooleanField(default=True, help_text='Whether album is public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gallery_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Album',
                'verbose_name_plural': 'Gallery Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Media title', max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Type of media', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Image file', null=True, upload_to=gallery.models.GalleryMedia.gallery_media_upload_path)),
                ('video_url', models.URLField(blank=True, help_text='Video URL (for external videos)')),
                ('is_public', models.BooleanField(default=True, help_text='Whether media is public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(help_text='Associated album', on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='gallery.galleryalbum')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_gallery_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Media',
                'verbose_name_plural': 'Gallery Media',
                'ordering': ['-created_at'],
            },
        ),
    ]
