# Generated by Django 5.2.6 on 2025-10-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryalbum_gallerymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='description',
            field=models.TextField(blank=True, help_text='Media description'),
        ),
    ]
