# Generated by Django 5.2.6 on 2025-10-01 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallerymedia_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymedia',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Associated album (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='gallery.galleryalbum'),
        ),
    ]
