# Generated by Django 5.2.5 on 2025-09-03 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_ASSIGNMENT', 'Role Assignment'), ('ROLE_REMOVAL', 'Role Removal'), ('PERMISSION_CHANGE', 'Permission Change'), ('EMAIL_VERIFICATION', 'Email Verification'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('ROLE_REQUEST_APPROVED', 'Role Request Approved'), ('ROLE_REQUEST_REJECTED', 'Role Request Rejected'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected')], max_length=50),
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('ORGANIZER', 'Event Organizer'), ('COACH', 'Coach'), ('ATHLETE', 'Athlete')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text="User's reason for requesting this role")),
                ('organization_name', models.CharField(blank=True, help_text='For Organizer role', max_length=200)),
                ('organization_website', models.URLField(blank=True, help_text='For Organizer role')),
                ('coaching_experience', models.TextField(blank=True, help_text='For Coach role')),
                ('sport_discipline', models.CharField(blank=True, help_text='For Athlete role', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Request',
                'verbose_name_plural': 'Role Requests',
                'db_table': 'accounts_role_request',
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_ro_user_id_a3bcdb_idx'), models.Index(fields=['requested_role', 'status'], name='accounts_ro_request_96a4d9_idx'), models.Index(fields=['status', 'created_at'], name='accounts_ro_status_bb4cbf_idx'), models.Index(fields=['created_at'], name='accounts_ro_created_3ff66a_idx')],
            },
        ),
    ]
