# Generated by Django 5.2.5 on 2025-08-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250821_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('ADMIN', 'Administrator'), ('ORGANIZER', 'Event Organizer'), ('ATHLETE', 'Athlete'), ('COACH', 'Coach'), ('MANAGER', 'Team Manager'), ('SPECTATOR', 'Spectator'), ('VOLUNTEER', 'Volunteer'), ('REFEREE', 'Referee'), ('MEDICAL', 'Medical Staff'), ('SUPPORT', 'Support Staff')], max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary role for this user')),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_manage_teams', models.BooleanField(default=False)),
                ('can_manage_fixtures', models.BooleanField(default=False)),
                ('can_manage_results', models.BooleanField(default=False)),
                ('can_manage_payments', models.BooleanField(default=False)),
                ('can_manage_content', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.user')),
            ],
            options={
                'db_table': 'accounts_user_role',
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_primary'], name='accounts_user_role_user_id_is_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role_type', 'is_active'], name='accounts_user_role_role_type_is_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role_type')},
        ),
    ]
