# Generated by Django 5.2.6 on 2025-09-24 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_organizer_application'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rolerequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='rolerequest',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='organizerapplication',
            options={'verbose_name': 'Organizer Application', 'verbose_name_plural': 'Organizer Applications'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_created_4734df_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_stripe__0997f8_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AlterField(
            model_name='organizerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizerapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SPECTATOR', 'Spectator'), ('ORGANIZER', 'Organizer'), ('COACH', 'Coach'), ('ATHLETE', 'Athlete'), ('ADMIN', 'Admin')], db_index=True, default='SPECTATOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='organizerapplication',
            index=models.Index(fields=['status'], name='accounts_or_status_6eed6a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizerapplication',
            index=models.Index(fields=['user', 'status'], name='accounts_or_user_id_cf99f9_idx'),
        ),
        migrations.AddIndex(
            model_name='organizerapplication',
            index=models.Index(fields=['created_at'], name='accounts_or_created_d110c0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AlterModelTable(
            name='organizerapplication',
            table='accounts_organizer_application',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='RoleRequest',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
