# Generated by Django 5.2.6 on 2025-10-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_athlete_coach_applications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleteapplication',
            options={'verbose_name': 'Athlete Application', 'verbose_name_plural': 'Athlete Applications'},
        ),
        migrations.AlterModelOptions(
            name='coachapplication',
            options={'verbose_name': 'Coach Application', 'verbose_name_plural': 'Coach Applications'},
        ),
        migrations.RenameIndex(
            model_name='athleteapplication',
            new_name='accounts_at_status_31672a_idx',
            old_name='accounts_at_status_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='athleteapplication',
            new_name='accounts_at_user_id_d4e54d_idx',
            old_name='accounts_at_user_id_5e6f7g_idx',
        ),
        migrations.RenameIndex(
            model_name='athleteapplication',
            new_name='accounts_at_created_c3e537_idx',
            old_name='accounts_at_created_6f7g8h_idx',
        ),
        migrations.RenameIndex(
            model_name='coachapplication',
            new_name='accounts_co_status_b432c7_idx',
            old_name='accounts_co_status_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='coachapplication',
            new_name='accounts_co_user_id_173142_idx',
            old_name='accounts_co_user_id_2b3c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='coachapplication',
            new_name='accounts_co_created_1a4a5d_idx',
            old_name='accounts_co_created_3c4d5e_idx',
        ),
    ]
