# Generated by Django 5.2.5 on 2025-08-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_userrole_assigned_by_extras'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrole',
            name='accounts_user_role_user_id_is_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='accounts_us_role_ty_9a216b_idx',
            old_name='accounts_user_role_role_type_is_active_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role_type', 'context_type', 'context_id')},
        ),
        # 'role' column already exists in accounts_user; skip adding to avoid duplicate column error
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_3e57b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['context_type', 'context_id'], name='accounts_us_context_09aa51_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['assigned_at'], name='accounts_us_assigne_5f6e61_idx'),
        ),
    ]
