# Generated by Django 5.2.6 on 2025-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_athleteapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerapplication',
            name='business_doc',
            field=models.FileField(blank=True, help_text='Business registration or organization document', null=True, upload_to='organizer_documents/business/'),
        ),
        migrations.AddField(
            model_name='organizerapplication',
            name='organization_name',
            field=models.CharField(blank=True, default='', help_text='Name of the organization', max_length=255),
        ),
    ]
