# Generated by Django 5.2.5 on 2025-09-03 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_auditlog_action_rolerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kyc_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('waived', 'Waived'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_issuer', models.CharField(blank=True, max_length=100)),
                ('document_expiry', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Profile',
                'verbose_name_plural': 'KYC Profiles',
                'db_table': 'kyc_profile',
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_front', 'ID Front'), ('id_back', 'ID Back'), ('selfie', 'Selfie'), ('passport', 'Passport'), ('driver_license', 'Driver License'), ('national_id', 'National ID'), ('proof_of_address', 'Proof of Address')], max_length=20)),
                ('file', models.FileField(upload_to='kyc_documents/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycprofile')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'kyc_document',
            },
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['status'], name='kyc_profile_status_6a8c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['user', 'status'], name='kyc_profile_user_id_312d35_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['reviewed_at'], name='kyc_profile_reviewe_16fa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['created_at'], name='kyc_profile_created_2788a9_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['kyc_profile', 'document_type'], name='kyc_documen_kyc_pro_aeb99b_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['is_verified'], name='kyc_documen_is_veri_73d296_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['created_at'], name='kyc_documen_created_bd9cd3_idx'),
        ),
    ]
