# Generated by Django 5.2.6 on 2025-10-01 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('role_approval', 'Role Approval'), ('role_rejection', 'Role Rejection'), ('event_reminder', 'Event Reminder'), ('registration_confirmed', 'Registration Confirmed'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('fixture_updated', 'Fixture Updated'), ('result_published', 'Result Published'), ('system_maintenance', 'System Maintenance'), ('announcement', 'Announcement')], max_length=50)),
                ('subject_template', models.CharField(help_text='Email subject template', max_length=200)),
                ('body_template', models.TextField(help_text='Notification body template')),
                ('variables', models.JSONField(default=list, help_text='Available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='notificatio_templat_89d547_idx')],
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_type', models.CharField(choices=[('all', 'All Users'), ('role', 'By Role'), ('event', 'Event Participants'), ('custom', 'Custom Query')], max_length=20)),
                ('target_criteria', models.JSONField(default=dict, help_text='Criteria for targeting users')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_ca8ad6_idx'), models.Index(fields=['created_by', 'status'], name='notificatio_created_720520_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationUnread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of unread notifications')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_unread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Unread Count',
                'verbose_name_plural': 'Notification Unread Counts',
                'indexes': [models.Index(fields=['user', 'count'], name='notificatio_user_id_b6d3a0_idx')],
            },
        ),
    ]
